"use client"

import { useEffect, useState } from "react"
import { Trophy, Award as AwardIcon, Star, Calendar, Crown, TrendingUp, Sparkles, Shield, Target } from "lucide-react"
import Link from "next/link"

interface Award {
  id: string
  name: string
  category: string
  icon: string
  description: string
  awardedAt: string
  isAutoGenerated: boolean
  winner: {
    name: string
    profile: { username: string }
  }
  season: {
    name: string
    id: string
  }
}

const awardIcons: Record<string, React.ReactNode> = {
  Crown: <Crown className="h-8 w-8 text-yellow-500" />,
  Trophy: <Trophy className="h-8 w-8 text-orange-500" />,
  Shield: <Shield className="h-8 w-8 text-blue-500" />,
  Star: <Star className="h-8 w-8 text-purple-500" />,
  TrendingUp: <TrendingUp className="h-8 w-8 text-green-500" />,
  Sparkles: <Sparkles className="h-8 w-8 text-pink-500" />,
  Target: <Target className="h-8 w-8 text-red-500" />,
}

const categoryColors: Record<string, string> = {
  CHAMPION: "from-yellow-500/20 to-amber-500/20 border-yellow-500/30",
  GOLDEN_BOOT: "from-orange-500/20 to-red-500/20 border-orange-500/30",
  GOLDEN_GLOVE: "from-blue-500/20 to-cyan-500/20 border-blue-500/30",
  PLAYER_OF_THE_SEASON: "from-purple-500/20 to-pink-500/20 border-purple-500/30",
  MOST_IMPROVED: "from-green-500/20 to-emerald-500/20 border-green-500/30",
  BEST_NEWCOMER: "from-pink-500/20 to-rose-500/20 border-pink-500/30",
  TOP_PLAYMAKER: "from-red-500/20 to-orange-500/20 border-red-500/30",
  MOST_CONSISTENT: "from-indigo-500/20 to-violet-500/20 border-indigo-500/30",
}

export default function AwardsPage() {
  const [awards, setAwards] = useState<Award[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    fetchAwards()
  }, [])

  async function fetchAwards() {
    const res = await fetch("/api/awards")
    const data = await res.json()
    setAwards(Array.isArray(data) ? data : [])
    setLoading(false)
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-gray-400">Loading awards...</div>
      </div>
    )
  }

  const groupedAwards = awards.reduce((acc, award) => {
    const season = award.season.name
    if (!acc[season]) acc[season] = []
    acc[season].push(award)
    return acc
  }, {} as Record<string, Award[]>)

  return (
    <div className="space-y-8">
      {/* Header */}
      <div>
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold text-white">🏆 Awards & Trophies</h1>
            <p className="text-gray-400 mt-1">Celebrating the best players each season</p>
          </div>
          <Link
            href="/hall-of-fame"
            className="text-sm text-indigo-400 hover:text-indigo-300 transition-all flex items-center gap-1"
          >
            View Hall of Fame →
          </Link>
        </div>
      </div>

      {/* Awards by Season */}
      {Object.keys(groupedAwards).length === 0 ? (
        <div className="text-center py-12 bg-gray-800 rounded-xl border border-gray-700">
          <Trophy className="h-16 w-16 text-gray-600 mx-auto mb-4" />
          <h3 className="text-xl font-semibold text-white mb-2">No Awards Yet</h3>
          <p className="text-gray-400">Awards will appear here after each season ends.</p>
        </div>
      ) : (
        Object.entries(groupedAwards).map(([seasonName, seasonAwards]) => (
          <div key={seasonName} className="bg-gray-800 rounded-xl border border-gray-700 overflow-hidden">
            <div className="bg-gradient-to-r from-indigo-600 to-purple-600 px-6 py-4">
              <h2 className="text-xl font-bold text-white flex items-center gap-2">
                <Calendar className="h-5 w-5" />
                {seasonName}
              </h2>
              <p className="text-sm text-white/70">{seasonAwards.length} awards</p>
            </div>
            <div className="divide-y divide-gray-700">
              {seasonAwards.map((award) => {
                const winnerName = award.winner.profile?.username || award.winner.name
                const Icon = awardIcons[award.icon] || <AwardIcon className="h-8 w-8 text-gray-400" />
                const colorClass = categoryColors[award.category] || "from-gray-500/20 to-gray-600/20 border-gray-500/30"
                
                return (
                  <div key={award.id} className={`flex items-center gap-4 p-4 hover:bg-gray-700/50 transition-colors border-l-4 ${colorClass}`}>
                    <div className="flex-shrink-0">
                      {Icon}
                    </div>
                    <div className="flex-1">
                      <h3 className="font-semibold text-white">{award.name}</h3>
                      <p className="text-sm text-gray-400">Winner: {winnerName}</p>
                      {award.description && (
                        <p className="text-xs text-gray-500 mt-1">{award.description}</p>
                      )}
                      <div className="flex gap-2 mt-1">
                        {award.isAutoGenerated && (
                          <span className="text-xs bg-green-500/20 text-green-400 px-2 py-0.5 rounded-full">Auto-generated</span>
                        )}
                      </div>
                    </div>
                    <div className="text-right">
                      <p className="text-sm font-medium text-indigo-400">{new Date(award.awardedAt).toLocaleDateString()}</p>
                    </div>
                  </div>
                )
              })}
            </div>
          </div>
        ))
      )}
    </div>
  )
}