"use client"

import { useEffect, useState } from "react"
import { useSession } from "next-auth/react"
import { useRouter } from "next/navigation"
import { 
  Trophy, Crown, Star, Shield, Sparkles, TrendingUp, Target, 
  Plus, Edit, Trash2, Calendar, Users, RefreshCw, Award,
  CheckCircle, XCircle, Eye
} from "lucide-react"
import toast from "react-hot-toast"

interface Award {
  id: string
  name: string
  category: string
  icon: string
  description: string
  awardedAt: string
  isAutoGenerated: boolean
  winner: {
    name: string
    profile: { username: string }
  }
  season: {
    name: string
    id: string
  }
}

interface Season {
  id: string
  name: string
  isActive: boolean
}

const iconMap: Record<string, React.ReactNode> = {
  Crown: <Crown className="h-5 w-5 text-yellow-500" />,
  Trophy: <Trophy className="h-5 w-5 text-amber-500" />,
  Shield: <Shield className="h-5 w-5 text-blue-500" />,
  Star: <Star className="h-5 w-5 text-purple-500" />,
  TrendingUp: <TrendingUp className="h-5 w-5 text-green-500" />,
  Sparkles: <Sparkles className="h-5 w-5 text-pink-500" />,
  Target: <Target className="h-5 w-5 text-red-500" />,
  Award: <Award className="h-5 w-5 text-indigo-500" />,
}

export default function AdminAwardsPage() {
  const { data: session, status } = useSession()
  const router = useRouter()
  const [awards, setAwards] = useState<Award[]>([])
  const [seasons, setSeasons] = useState<Season[]>([])
  const [loading, setLoading] = useState(true)
  const [selectedSeason, setSelectedSeason] = useState<string>("all")
  const [generating, setGenerating] = useState(false)

  useEffect(() => {
    if (status === "loading") return
    
    if (!session) {
      router.push("/auth/signin")
      return
    }
    
    if (session.user?.role !== "ADMIN") {
      router.push("/dashboard")
      return
    }
  }, [session, status, router])

  useEffect(() => {
    if (session?.user?.role === "ADMIN") {
      fetchData()
    }
  }, [session])

  async function fetchData() {
    await Promise.all([fetchSeasons(), fetchAwards()])
    setLoading(false)
  }

  async function fetchSeasons() {
    const res = await fetch("/api/seasons")
    const data = await res.json()
    setSeasons(Array.isArray(data) ? data : [])
  }

  async function fetchAwards() {
    const res = await fetch("/api/awards")
    const data = await res.json()
    setAwards(Array.isArray(data) ? data : [])
  }

  async function generateAwards() {
    if (!selectedSeason || selectedSeason === "all") {
      toast.error("Please select a specific season")
      return
    }

    setGenerating(true)

    const res = await fetch("/api/admin/awards/generate", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ seasonId: selectedSeason })
    })

    const data = await res.json()

    if (res.ok) {
      toast.success(data.message || "Awards generated successfully!")
      fetchAwards()
    } else {
      toast.error(data.error || "Failed to generate awards")
    }

    setGenerating(false)
  }

  async function deleteAward(id: string) {
    if (!confirm("Are you sure you want to delete this award?")) return

    const res = await fetch(`/api/awards/${id}`, { method: "DELETE" })
    if (res.ok) {
      toast.success("Award deleted")
      fetchAwards()
    } else {
      toast.error("Failed to delete")
    }
  }

  async function regenerateAwards() {
    if (!selectedSeason || selectedSeason === "all") {
      toast.error("Please select a specific season")
      return
    }

    if (!confirm("This will delete all existing awards for this season and regenerate them. Continue?")) return

    setGenerating(true)

    // First delete existing awards
    await fetch("/api/admin/awards/generate", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ 
        seasonId: selectedSeason,
        action: "delete" 
      })
    })

    // Then generate new ones
    const res = await fetch("/api/admin/awards/generate", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ seasonId: selectedSeason })
    })

    const data = await res.json()

    if (res.ok) {
      toast.success(data.message || "Awards regenerated successfully!")
      fetchAwards()
    } else {
      toast.error(data.error || "Failed to regenerate awards")
    }

    setGenerating(false)
  }

  const filteredAwards = selectedSeason === "all" 
    ? awards 
    : awards.filter(a => a.season.id === selectedSeason)

  if (status === "loading" || loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-gray-400">Loading awards...</div>
      </div>
    )
  }

  if (session?.user?.role !== "ADMIN") {
    return null
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap justify-between items-center gap-4">
        <div>
          <h1 className="text-2xl font-bold text-white flex items-center gap-2">
            <Award className="h-6 w-6 text-yellow-500" />
            Awards Management
          </h1>
          <p className="text-gray-400 mt-1">Manage awards and trophies for each season</p>
        </div>
      </div>

      <div className="bg-gray-800 rounded-xl border border-gray-700 p-6">
        <div className="flex flex-wrap gap-4 items-end">
          <div className="flex-1 min-w-[200px]">
            <label className="block text-sm font-medium text-gray-300 mb-1">Select Season</label>
            <select
              value={selectedSeason}
              onChange={(e) => setSelectedSeason(e.target.value)}
              className="w-full bg-gray-700 border border-gray-600 rounded-lg px-4 py-2 text-white focus:outline-none focus:border-indigo-500"
            >
              <option value="all">All Seasons</option>
              {seasons.map(s => (
                <option key={s.id} value={s.id}>
                  {s.name} {s.isActive ? "(Active)" : ""}
                </option>
              ))}
            </select>
          </div>
          <div className="flex gap-2">
            <button
              onClick={generateAwards}
              disabled={generating || selectedSeason === "all"}
              className="bg-green-600 text-white px-4 py-2 rounded-lg flex items-center gap-2 hover:bg-green-700 transition-all disabled:opacity-50"
            >
              <RefreshCw size={16} className={generating ? "animate-spin" : ""} />
              {generating ? "Generating..." : "Generate Awards"}
            </button>
            {selectedSeason !== "all" && filteredAwards.length > 0 && (
              <button
                onClick={regenerateAwards}
                disabled={generating}
                className="bg-yellow-600 text-white px-4 py-2 rounded-lg flex items-center gap-2 hover:bg-yellow-700 transition-all disabled:opacity-50"
              >
                <RefreshCw size={16} />
                Regenerate
              </button>
            )}
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <div className="bg-gray-800 rounded-lg p-4 border border-gray-700">
          <p className="text-2xl font-bold text-white">{awards.length}</p>
          <p className="text-sm text-gray-400">Total Awards</p>
        </div>
        <div className="bg-green-500/10 rounded-lg p-4 border border-green-500/20">
          <p className="text-2xl font-bold text-green-400">{awards.filter(a => a.isAutoGenerated).length}</p>
          <p className="text-sm text-gray-400">Auto-Generated</p>
        </div>
        <div className="bg-blue-500/10 rounded-lg p-4 border border-blue-500/20">
          <p className="text-2xl font-bold text-blue-400">{awards.filter(a => !a.isAutoGenerated).length}</p>
          <p className="text-sm text-gray-400">Manual</p>
        </div>
      </div>

      {filteredAwards.length === 0 ? (
        <div className="text-center py-12 bg-gray-800 rounded-xl border border-gray-700">
          <Award className="h-16 w-16 text-gray-600 mx-auto mb-4" />
          <h3 className="text-xl font-semibold text-white mb-2">No Awards Yet</h3>
          <p className="text-gray-400">Select a season and click "Generate Awards" to create them automatically.</p>
        </div>
      ) : (
        <div className="grid gap-4">
          {filteredAwards.map((award) => {
            const Icon = iconMap[award.icon] || <Award className="h-5 w-5 text-gray-400" />
            const winnerName = award.winner.profile?.username || award.winner.name

            return (
              <div key={award.id} className="bg-gray-800 rounded-xl border border-gray-700 p-5 hover:border-gray-600 transition-all">
                <div className="flex flex-wrap justify-between items-start gap-4">
                  <div className="flex items-center gap-4">
                    <div className="p-2 bg-gray-700/50 rounded-lg">
                      {Icon}
                    </div>
                    <div>
                      <div className="flex items-center gap-2 flex-wrap">
                        <h2 className="text-lg font-semibold text-white">{award.name}</h2>
                        <span className="text-xs bg-gray-700 px-2 py-0.5 rounded-full text-gray-300">
                          {award.category}
                        </span>
                        {award.isAutoGenerated && (
                          <span className="text-xs bg-green-500/20 text-green-400 px-2 py-0.5 rounded-full">Auto</span>
                        )}
                      </div>
                      <div className="flex items-center gap-4 mt-1 text-sm">
                        <span className="text-gray-400">Winner: <span className="text-white font-medium">{winnerName}</span></span>
                        <span className="text-gray-400">Season: <span className="text-white">{award.season.name}</span></span>
                        <span className="text-gray-400">Awarded: {new Date(award.awardedAt).toLocaleDateString()}</span>
                      </div>
                      {award.description && (
                        <p className="text-gray-400 text-sm mt-1">{award.description}</p>
                      )}
                    </div>
                  </div>
                  <div className="flex gap-2">
                    <button
                      onClick={() => deleteAward(award.id)}
                      className="text-red-400 hover:text-red-300 p-2 transition-all"
                    >
                      <Trash2 size={18} />
                    </button>
                  </div>
                </div>
              </div>
            )
          })}
        </div>
      )}
    </div>
  )
}